import { useEffect, useState } from 'react';
import { ArrowRight, BookOpen, ChartNoAxesCombined, Home as HomeIcon, MessagesSquare, MessageSquareText, Settings2, Bookmark, PanelLeftClose, Leaf, Sparkles, X, ArrowUpRight, Clock, Check, MoveRight } from 'lucide-react';
import { AppContext } from './context';
import type { Page } from './context';
import { emptyStore, readStore, STORAGE_KEY } from './storage';
import { coreScenarios } from '../shared/scenarios';
import { Notice, PageTitle } from './components';
import Practice from './Practice';
import Simulation from './Simulation';
import Review from './Review';
import { Collection, Progress, SettingsPage } from './Records';
import { useApp } from './context';
const nav=[{id:'home',label:'今日练习',icon:HomeIcon},{id:'practice',label:'情境练习',icon:MessageSquareText},{id:'simulation',label:'多轮模拟',icon:MessagesSquare},{id:'review',label:'聊天复盘',icon:BookOpen},{id:'collection',label:'错题与收藏',icon:Bookmark},{id:'progress',label:'学习记录',icon:ChartNoAxesCombined},{id:'settings',label:'设置',icon:Settings2}] as const;
function currentPage():Page{const id=location.hash.slice(1).split('?')[0];return nav.some(n=>n.id===id)?id as Page:'home';}
export default function App(){
  const [loaded]=useState(readStore);const [store,setStore]=useState(loaded.store);
  const [page,setPage]=useState<Page>(currentPage);const [toast,setToast]=useState('');const [menu,setMenu]=useState(false);
  const [aiReady,setAiReady]=useState<boolean|null>(null);const [accessRequired,setAccessRequired]=useState(false);const [statusError,setStatusError]=useState('');
  const [storageBlocked,setStorageBlocked]=useState(!!loaded.error);
  useEffect(()=>{const onHash=()=>{setPage(currentPage());setMenu(false);window.scrollTo({top:0,behavior:'instant'});};window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash);},[]);
  useEffect(()=>{if(storageBlocked)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(store));}catch{setStorageBlocked(true);setToast('本地保存失败，可能存储空间不足。请导出记录备份。');}},[store,storageBlocked]);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(timer);},[toast]);
  useEffect(()=>{fetch('/api/status').then(async r=>{if(!r.ok)throw Error();const data=await r.json();setAiReady(data.aiConfigured===true);setAccessRequired(data.accessRequired===true);}).catch(()=>setStatusError('无法连接服务端，请确认项目已启动；刷新后可重试。'));},[]);
  useEffect(()=>{document.documentElement.dataset.motion=store.settings.reducedMotion?'reduced':'normal';},[store.settings.reducedMotion]);
  const go=(p:Page)=>{location.hash=p;if(page===p){setPage(p);setMenu(false);window.scrollTo({top:0,behavior:'instant'});}};
  const openPractice=(id?:string)=>{if(id){setStore(s=>({...s,draft:{scenarioId:id,answer:'',silence:false,hints:0,revised:false,revealed:false}}));}else if(!store.draft||store.draft.savedId){const done=new Set(store.records.map(r=>r.scenarioId));const next=coreScenarios.find(s=>!done.has(s.id))??coreScenarios[0];setStore(s=>({...s,draft:{scenarioId:next.id,answer:'',silence:false,hints:0,revised:false,revealed:false}}));}go('practice');};
  return <AppContext.Provider value={{store,setStore,notify:setToast,go,openPractice,aiReady,accessRequired}}><div className="app-shell"><aside className={`sidebar ${menu?'open':''}`}><a href="#home" className="brand" onClick={()=>setMenu(false)}><span className="brand-mark"><MessagesSquare size={25}/></span><span>聊天练习室<small>给表达一点练习的空间</small></span></a><div className="sidebar-caption">你的练习空间</div><nav>{nav.map(n=><a href={`#${n.id}`} onClick={()=>setMenu(false)} key={n.id} className={page===n.id?'active':''} aria-current={page===n.id?'page':undefined}><n.icon size={19}/><span>{n.label}</span>{n.id==='collection'&&store.favorites.length>0&&<small>{store.favorites.length}</small>}</a>)}</nav><div className="sidebar-bottom"><div className="sidebar-note"><Leaf size={21}/><strong>练习更自在的交流</strong><p>不必每句话都完美。<br/>真诚，也给彼此留白。</p></div><button onClick={()=>go('settings')} className="mode-status"><span className={store.settings.mode==='demo'?'status-dot':'status-dot ai'}/>{store.settings.mode==='demo'?'本地演示模式':'AI 分析模式'}<ArrowUpRight size={15}/></button><small>记录保存在当前浏览器</small></div></aside>{menu&&<button className="sidebar-overlay" aria-label="关闭菜单" onClick={()=>setMenu(false)}/>}
  <div className="main-shell"><header className="topbar"><button className="mobile-menu icon-button" aria-label="打开菜单" onClick={()=>setMenu(!menu)}><PanelLeftClose size={22}/></button><div className="breadcrumb">我的练习空间 <span>/</span> <strong>{nav.find(n=>n.id===page)?.label}</strong></div><div className="topbar-right"><span className="adult-badge"><ShieldIcon/>成人虚构情境</span><span className="user-avatar">练</span></div></header><main>
  {loaded.error&&storageBlocked&&<Notice type="error">{loaded.error}<button className="text-button" onClick={()=>{if(confirm('确认使用新的空记录覆盖异常本地数据？请先到设置导出原始备份。')){setStore(emptyStore());setStorageBlocked(false);}}}>重新启用保存</button></Notice>}
  {!loaded.error&&storageBlocked&&<Notice type="error">浏览器本地保存失败。当前结果只保留在页面内存，刷新可能丢失；请到设置导出备份，清理存储空间后重新导入。</Notice>}
  {statusError&&<Notice type="error">{statusError}</Notice>}
  {page!=='home'&&<div className="mode-banner"><Sparkles size={15}/><span>{store.settings.mode==='demo'?'演示模式 · 内置题目、关键词规则与有限对话分支，不能完整理解自由输入。':'AI 模式 · 输入将通过服务端发送到已配置的外部 AI 服务。'}</span><button onClick={()=>go('settings')}>设置 <ArrowRight size={13}/></button></div>}
  {page==='home'?<Home/>:page==='practice'?<Practice/>:page==='simulation'?<Simulation/>:page==='review'?<Review/>:page==='collection'?<Collection/>:page==='progress'?<Progress/>:<SettingsPage onStorageReset={()=>setStorageBlocked(false)}/>}
  </main><footer><span>慢慢聊，好好说。</span><span>练习比较，不是人格测量 · 不会自动跨设备同步</span></footer></div></div>{toast&&<div className="toast" role="status"><Check size={17}/>{toast}<button onClick={()=>setToast('')} aria-label="关闭提示"><X size={15}/></button></div>}</AppContext.Provider>;
}
function ShieldIcon(){return <span className="tiny-circle">✓</span>;}
function Home(){
  const {store,setStore,openPractice,go}=useApp();const completed=new Set(store.records.map(r=>r.scenarioId)).size;const independent=store.records.filter(r=>r.hints===0).length;
  const start=()=>{setStore(s=>({...s,timerEnd:Date.now()+600000}));openPractice();};
  const areas=[{icon:MessageSquareText,title:'一句话，也可以练好',text:'从破冰到邀约，在具体情境里找到自然的表达。',label:'情境练习',page:'practice' as Page,color:'green'},{icon:MessagesSquare,title:'把聊天慢慢接下去',text:'和不同风格的虚构角色聊一聊，练习听与说。',label:'多轮模拟',page:'simulation' as Page,color:'peach'},{icon:BookOpen,title:'回头看，才有新发现',text:'粘贴一段聊天，分清事实和猜测，找到下一步。',label:'聊天复盘',page:'review' as Page,color:'purple'}];
  const recommended=coreScenarios.filter(s=>!store.records.some(r=>r.scenarioId===s.id)).slice(0,3);
  return <><PageTitle eyebrow="A LITTLE PRACTICE, A LITTLE EASE" title="今天，也给表达一点时间" description="在这里，练习自然地开启、接住和结束一段聊天。" action={<span className="date-note">每天一点，不用着急 <Leaf size={16}/></span>}/>
  <section className="hero"><div className="hero-copy"><span className="hero-kicker"><span/>你的日常聊天练习空间</span><h2>慢慢聊，<br/>好好说<span>。</span></h2><p>不必寻找一句「完美回复」。<br/>从真实的情境开始，练习表达自己，也理解对方。</p><button className="primary large" onClick={start}><span>开始 10 分钟练习</span><ArrowRight size={19}/></button><div className="hero-meta"><Clock size={14}/> 一次只练一小步 <span>·</span> 无需配置 AI 即可体验</div></div><div className="hero-art" aria-hidden="true"><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><div className="art-dot dot-one"/><div className="art-dot dot-two"/><div className="art-message msg-first"><span className="art-face">◡</span><div><small>开启一个小话题</small><p>今天那家店的咖啡还不错 ☕</p></div></div><div className="art-message msg-second"><div><small>接住一点小日常</small><p>真的！下次想试试它的拿铁。</p></div><span className="art-face mint">◡</span></div><div className="art-caption"><Sparkles size={15}/> 真诚一点，轻松一点</div><svg className="plant" viewBox="0 0 150 160"><path d="M73 136C75 105 76 70 77 25" fill="none" stroke="#7a8c6c" strokeWidth="4"/><path d="M76 73C34 69 28 34 35 24C66 21 83 47 76 73Z" fill="#a9b59a"/><path d="M76 98C118 97 137 68 128 51C95 46 77 68 76 98Z" fill="#8c9f7e"/><path d="M76 47C96 35 103 8 90 3C68 12 64 27 76 47Z" fill="#c0c9ad"/><path d="M46 126H108L99 160H55Z" fill="#e4c6aa"/></svg></div></section>
  <div className="home-metrics"><div><span>已完成情境</span><strong>{completed}<small> 道</small></strong></div><div><span>独立完成练习</span><strong>{independent}<small> 次</small></strong></div><div><span>多轮模拟</span><strong>{store.sessions.length}<small> 次</small></strong></div><button onClick={()=>go('progress')}>查看我的学习记录 <ArrowUpRight size={17}/></button></div>
  {store.draft&&!store.draft.savedId&&<div className="continue-card"><div><span className="tag green">继续上次</span><strong>{coreScenarios.find(s=>s.id===store.draft?.scenarioId)?.title??'未完成的情境练习'}</strong><p>输入和提示进度已留在当前浏览器。</p></div><button className="secondary" onClick={()=>openPractice()}>接着练 <MoveRight size={16}/></button></div>}
  {store.sim&&!store.sim.recap&&<div className="continue-card"><div><span className="tag green">继续模拟</span><strong>{store.sim.config.goal} · 已聊 {store.sim.messages.filter(m=>m.role==='me').length} 轮</strong><p>虚构对话和角色资料已经保留，可以继续或结束并复盘。</p></div><button className="secondary" onClick={()=>go('simulation')}>接着聊 <MoveRight size={16}/></button></div>}
  <div className="section-heading"><h2>用适合你的方式练习</h2><span>表达、倾听与分寸，慢慢积累</span></div><div className="path-grid">{areas.map(a=><button className="path-card" key={a.page} onClick={()=>a.page==='practice'?openPractice():go(a.page)}><span className={`path-icon ${a.color}`}><a.icon size={23}/></span><h3>{a.title}</h3><p>{a.text}</p><div>{a.label}<ArrowRight size={17}/></div></button>)}</div>
  <div className="section-heading"><h2>从这些小情境开始</h2><button className="text-button" onClick={()=>go('practice')}>全部 36 道题 <ArrowRight size={15}/></button></div><div className="recommend-grid">{(recommended.length?recommended:coreScenarios.slice(0,3)).map((s,i)=><button key={s.id} className="recommend-card" onClick={()=>openPractice(s.id)}><div><span className="tag">{s.level} · {s.category}</span><span className="recommend-number">0{i+1}</span></div><h3>{s.title}</h3><p>{s.goal}</p><span className="recommend-link">试着回一句 <ArrowUpRight size={16}/></span></button>)}</div>
  <div className="home-principle"><Leaf size={22}/><p><strong>聊天是两个人的事。</strong> 练习的目标是表达清楚、相互了解，也看见彼此是否愿意继续。</p></div><Notice>当前为{store.settings.mode==='demo'?'本地演示模式：分析使用有限规则，对话使用预设分支。真正的自由输入分析和连续对话，需要在服务端配置 AI。':'AI 模式：练习输入会发送到服务端配置的 AI 服务，建议只使用匿名内容。'}</Notice></>;
}
