import { useRef, useState } from 'react';
import { ArrowRight, Bookmark, Check, Download, Flag, FolderHeart, RotateCcw, Settings2, Trash2, Upload } from 'lucide-react';
import { useApp } from './context';
import { coreScenarios, getScenario, scenarios } from '../shared/scenarios';
import { dimensions, skills } from '../shared/types';
import type { Skill } from '../shared/types';
import { BubbleList, Empty, FeedbackView, Notice, PageTitle, RecapView } from './components';
import { emptyStore, parseImport, STORAGE_KEY } from './storage';
import { setAccessToken } from './api';
const date=(at:string)=>new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Shanghai'}).format(new Date(at));
export function Collection(){
  const {store,setStore,openPractice}=useApp();const [tab,setTab]=useState('需再练');const [expanded,setExpanded]=useState('');
  const latest=new Map(store.records.map(r=>[r.scenarioId,r]));
  const wrong=[...latest.values()].filter(r=>r.feedback.issues.length>0||r.feedback.scores.some(s=>s.value<=2));
  const ids=tab==='收藏'?store.favorites:wrong.map(r=>r.scenarioId);
  return <><PageTitle eyebrow="MY COLLECTION" title="把值得再练的，留在这里" description="错题来自本工具的练习反馈，也可以收藏想继续琢磨的情境。"/><div className="tabs collection-tabs">{['需再练','收藏'].map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?'active':''}>{t}<span>{t==='收藏'?store.favorites.length:wrong.length}</span></button>)}</div>
  {!ids.length?<Empty title={tab==='收藏'?'还没有收藏的情境':'暂时没有需要再练的题目'} text={tab==='收藏'?'在情境右上角点书签，把喜欢的题留起来。':'完成练习后，相关问题会在这里汇集。评分仅作练习比较。'} action={<button className="primary" onClick={()=>openPractice()}>去练一句 <ArrowRight size={16}/></button>}/>:<div className="collection-list">{ids.map(id=>{const q=getScenario(id);const r=latest.get(id);if(!q)return null;const transfer=scenarios.find(s=>s.transfer&&s.focus===(r?.feedback.issues[0]??q.focus));return <section className="collection-card" key={id}><div className="collection-main"><span className="path-icon green"><FolderHeart size={22}/></span><div><span className="tag">{q.level} · {q.category}</span><h3>{q.title}</h3><p>{r?r.feedback.summary:q.goal}</p>{r&&<small>{r.hints===0?'独立完成':'借助提示'} · {date(r.at)} · {r.mode==='demo'?'演示规则':'AI 分析'}</small>}</div><button className="icon-button" aria-label={store.favorites.includes(id)?'取消收藏':'收藏本题'} onClick={()=>setStore(s=>({...s,favorites:s.favorites.includes(id)?s.favorites.filter(x=>x!==id):[...s.favorites,id]}))}><Bookmark size={18} fill={store.favorites.includes(id)?'currentColor':'none'}/></button></div><div className="collection-actions">{r&&<button className="text-button" onClick={()=>setExpanded(expanded===id?'':id)}>{expanded===id?'收起反馈':'查看我的回答'}</button>}<button className="secondary" onClick={()=>openPractice(id)}><RotateCcw size={15}/>重做本题</button>{transfer&&<button className="primary" onClick={()=>openPractice(transfer.id)}>换个相似情境 <ArrowRight size={15}/></button>}</div>{expanded===id&&r&&<div className="saved-feedback"><blockquote>{r.silence?'（选择不继续发消息）':r.answer}</blockquote><FeedbackView feedback={r.feedback} original={r.original?.feedback} full source={r.mode}/></div>}</section>;})}</div>}
  </>;
}
export function Progress(){
  const {store,openPractice}=useApp();const [dimension,setDimension]=useState<(typeof dimensions)[number]>(dimensions[0]);const [tab,setTab]=useState('情境');const [expanded,setExpanded]=useState('');
  const independent=store.records.filter(r=>r.hints===0).length;const done=new Set(store.records.filter(r=>!getScenario(r.scenarioId)?.transfer).map(r=>r.scenarioId)).size;
  const points=store.records.slice(-12).map(r=>r.feedback.scores.find(s=>s.dimension===dimension)?.value??1);
  const counts=new Map<Skill,number>();store.records.slice(-20).forEach(r=>r.feedback.issues.forEach(issue=>counts.set(issue,(counts.get(issue)??0)+1)));
  const recommendations=[...counts].sort((a,b)=>b[1]-a[1]).slice(0,3);
  return <><PageTitle eyebrow="LEARNING JOURNAL" title="看见一点点积累" description="看完成情况与练习变化，不排名，也不把分数当作真实情商。"/><div className="stats-grid"><div><span>情境完成</span><strong>{done}<small> / 36 道</small></strong><p>重复练习单独计次</p></div><div><span>独立完成</span><strong>{independent}<small> / {store.records.length} 次</small></strong><p>未使用逐级提示</p></div><div><span>修改练习</span><strong>{store.records.filter(r=>r.original).length}<small> 次</small></strong><p>先自己改，再看参考</p></div><div><span>模拟 / 文本复盘</span><strong>{store.sessions.length}<small> / {store.reviews.length} 次</small></strong><p>文本复盘仅计主动保存</p></div></div>
  <section className="panel trend-panel"><div className="section-heading"><h2>能力练习趋势</h2><span>最近 {points.length} 次情境练习</span></div><div className="trend-legend">{dimensions.map(d=><button key={d} onClick={()=>setDimension(d)} className={dimension===d?'active':''}>{d}</button>)}</div>{points.length<2?<Empty title={points.length?'再完成一次，就能比较变化':'趋势从第一条记录开始'} text="同一维度只反映本工具评估，演示规则和 AI 评分也可能不同。"/>:<div className="chart-wrap"><svg viewBox="0 0 800 210" role="img" aria-label={`${dimension}最近${points.length}次评分：${points.join('、')}`}><defs><linearGradient id="chartFade" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#507565" stopOpacity=".17"/><stop offset="100%" stopColor="#507565" stopOpacity="0"/></linearGradient></defs>{[1,2,3,4,5].map(n=><g key={n}><line x1="38" y1={188-(n-1)*40} x2="782" y2={188-(n-1)*40} stroke="#e8e9e4" strokeDasharray="4 5"/><text x="15" y={192-(n-1)*40} fill="#8a8e87" fontSize="12">{n}</text></g>)}<polygon fill="url(#chartFade)" points={`45,188 ${points.map((v,i)=>`${45+i*(730/(points.length-1))},${188-(v-1)*40}`).join(' ')} 775,188`}/><polyline fill="none" stroke="#507565" strokeWidth="3" strokeLinejoin="round" points={points.map((v,i)=>`${45+i*(730/(points.length-1))},${188-(v-1)*40}`).join(' ')}/>{points.map((v,i)=><g key={i}><circle cx={45+i*(730/(points.length-1))} cy={188-(v-1)*40} r="5" fill="#507565" stroke="white" strokeWidth="2"/><title>第{i+1}次：{v}分</title></g>)}</svg><div className="chart-labels"><span>较早练习</span><span>最近练习</span></div></div>}<p className="tiny muted">1–5 分仅用于练习比较。这里展示每次最终回复的评估，使用提示的练习也包含在内；不同情境、演示规则与 AI 评估不能视为精确心理测量。</p></section>
  <section className="panel"><div className="section-heading"><h2>下一步，练一个具体方向</h2><Flag size={18}/></div>{recommendations.length?<div className="specialty-grid">{recommendations.map(([skill,count])=>{const q=scenarios.find(s=>s.transfer&&s.focus===skill)??scenarios.find(s=>s.focus===skill)!;return <button key={skill} onClick={()=>openPractice(q.id)}><span className="tag sand">最近 20 次中出现 {count} 次</span><h3>{skill}</h3><p>{q.goal}</p><span>用新情境检验 <ArrowRight size={15}/></span></button>;})}</div>:<p className="muted">暂没有重复问题可推荐。可以先完成几次练习；没有触发规则也不代表所有表达都已被理解。</p>}</section>
  <div className="section-heading"><h2>我的练习历史</h2><span>{store.records.length+store.sessions.length+store.reviews.length} 条保存记录</span></div><div className="tabs collection-tabs">{['情境','模拟','文本复盘'].map(t=><button key={t} onClick={()=>{setTab(t);setExpanded('');}} className={tab===t?'active':''}>{t}</button>)}</div>
  <div className="history-list">{tab==='情境'&&store.records.slice().reverse().map(r=><div className="history-row" key={r.id}><button className="history-trigger" onClick={()=>setExpanded(expanded===r.id?'':r.id)}><span className="history-icon"><Check size={17}/></span><div><strong>{getScenario(r.scenarioId)?.title??'情境练习'}</strong><small>{date(r.at)} · {r.hints===0?'独立完成':`使用 ${r.hints} 级提示`} · {r.mode==='demo'?'演示规则':'AI 分析'}{r.original?' · 已修改':''}</small></div><ArrowRight size={16}/></button>{expanded===r.id&&<><blockquote>{r.silence?'（选择不继续发消息）':r.answer}</blockquote><FeedbackView feedback={r.feedback} original={r.original?.feedback} full source={r.mode}/></>}</div>)}{tab==='模拟'&&store.sessions.slice().reverse().map(r=><div className="history-row" key={r.id}><button className="history-trigger" onClick={()=>setExpanded(expanded===r.id?'':r.id)}><span className="history-icon"><Check size={17}/></span><div><strong>{r.config.goal} · {r.messages.filter(m=>m.role==='me').length} 轮</strong><small>{date(r.at)} · {r.config.coach?'教练':'实战'}模式 · {r.mode==='demo'?'有限分支演示':'AI 对话'}</small></div><ArrowRight size={16}/></button>{expanded===r.id&&<><BubbleList messages={r.messages}/><RecapView recap={r.recap} demo={r.mode==='demo'}/></>}</div>)}{tab==='文本复盘'&&store.reviews.slice().reverse().map(r=><div className="history-row" key={r.id}><button className="history-trigger" onClick={()=>setExpanded(expanded===r.id?'':r.id)}><span className="history-icon"><Check size={17}/></span><div><strong>已主动保存的聊天复盘</strong><small>{date(r.at)} · {r.messages.length} 条消息 · {r.mode==='demo'?'演示规则':'AI 分析'}</small></div><ArrowRight size={16}/></button>{expanded===r.id&&<><BubbleList messages={r.messages}/><RecapView recap={r.recap} demo={r.mode==='demo'}/></>}</div>)}</div>
  {(tab==='情境'&&!store.records.length||tab==='模拟'&&!store.sessions.length||tab==='文本复盘'&&!store.reviews.length)&&<Empty title="这里还没有记录" text="完成情境或模拟后自动保存。真实聊天只有主动选择后才会出现在这里。"/>}
  </>;
}
export function SettingsPage({onStorageReset}:{onStorageReset:()=>void}){
  const {store,setStore,notify,aiReady,accessRequired}=useApp();const file=useRef<HTMLInputElement>(null);const [token,setToken]=useState('');const [error,setError]=useState('');
  const exportData=(original=false)=>{let content=JSON.stringify(store,null,2);if(original)try{content=localStorage.getItem(STORAGE_KEY)??content;}catch{}const url=URL.createObjectURL(new Blob([content],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`聊天练习室-${new Date().toISOString().slice(0,10)}${original?'-原始备份':''}.json`;a.click();URL.revokeObjectURL(url);notify('记录已导出；主动保存的真实聊天也包含在文件中，请妥善保管。');};
  const importData=async(f:File)=>{setError('');try{if(f.size>5_000_000)throw Error('文件超过 5 MB，请缩减后导入。');const imported=parseImport(await f.text());if(!confirm(`导入 ${imported.records.length} 次情境、${imported.sessions.length} 次模拟和 ${imported.reviews.length} 次文本复盘，将替换当前记录与设置。是否继续？`))return;setStore(imported);onStorageReset();notify('记录导入成功。');}catch(e){setError((e as Error).message);}finally{if(file.current)file.current.value='';}};
  const clear=()=>{if(!confirm('确定清空所有练习、收藏、未完成草稿与设置？此操作无法撤销，建议先导出备份。'))return;try{localStorage.removeItem(STORAGE_KEY);}catch{}setStore(emptyStore());setAccessToken('');setToken('');onStorageReset();notify('所有学习记录已清空。');};
  return <><PageTitle eyebrow="PREFERENCES" title="把练习空间调成你的样子" description="无需注册即可练习。学习记录只保存在当前浏览器，不会自动跨设备同步。"/>
  <section className="panel settings-panel"><div className="section-label"><Settings2 size={17}/>分析与对话模式</div><div className="mode-choice"><button className={store.settings.mode==='demo'?'selected':''} onClick={()=>setStore(s=>({...s,settings:{...s.settings,mode:'demo'}}))}><div><strong>本地演示模式 <span className="tag green">默认</span></strong><p>人工题库、关键词规则与有限对话分支。无需 API 密钥。</p></div></button><button className={store.settings.mode==='ai'?'selected':''} onClick={()=>setStore(s=>({...s,settings:{...s.settings,mode:'ai'}}))}><div><strong>AI 分析模式 <span className="tag">{aiReady===null?'状态未知':aiReady?'服务端已配置':'尚未配置'}</span></strong><p>自由输入分析与连续对话，由服务端调用外部 AI。</p></div></button></div><Notice>演示模式只能提示部分字词、长度和问题数量，可能漏判或误判。AI 也不能知道真实对方的内心；两种模式的评分都仅供练习比较。</Notice>{store.settings.mode==='ai'&&<><p className="muted">由部署者在服务端环境变量设置 AI_API_KEY、AI_BASE_URL 与 AI_MODEL，再重启服务。服务配置步骤见项目 README；请勿把 API 密钥输入网页或聊天。</p><label className="checkbox external-consent"><input type="checkbox" checked={store.settings.externalConsent} onChange={e=>setStore(s=>({...s,settings:{...s.settings,externalConsent:e.target.checked}}))}/>我了解情境输入和虚构模拟历史将发送到外部 AI 服务，同意启用；真实聊天会在提交前另行确认</label>{accessRequired&&<label className="field-label">服务访问口令（不是 AI 密钥，仅本次页面会话）<input type="password" autoComplete="off" value={token} onChange={e=>{setToken(e.target.value);setAccessToken(e.target.value);}} placeholder="部署者设置的 APP_ACCESS_TOKEN"/></label>}</>}
  </section><section className="panel settings-panel"><h2>学习记录与隐私</h2><p className="muted">情境练习、收藏和虚构模拟保存到浏览器 localStorage。真实聊天默认不保存，只有你主动勾选并点击保存后才写入。导出文件也会包含这些已保存文本。</p><div className="settings-actions"><button className="secondary" onClick={()=>exportData()}><Download size={17}/>导出学习记录</button><button className="secondary" onClick={()=>file.current?.click()}><Upload size={17}/>导入学习记录</button><button className="text-button" onClick={()=>exportData(true)}>导出原始备份</button><button className="danger" onClick={clear}><Trash2 size={16}/>清空学习记录</button><input className="sr-only" type="file" accept="application/json,.json" ref={file} aria-label="导入记录文件" onChange={e=>{const f=e.target.files?.[0];if(f)void importData(f);}}/></div>{error&&<Notice type="error">{error}</Notice>}<p className="tiny muted">导入会先校验格式，并确认后替换当前记录。清空会再次确认；使用隐私浏览或清理网站数据会失去本地记录。</p></section><section className="panel settings-panel"><h2>阅读偏好</h2><label className="checkbox"><input type="checkbox" checked={store.settings.reducedMotion} onChange={e=>setStore(s=>({...s,settings:{...s.settings,reducedMotion:e.target.checked}}))}/>减少界面动效</label></section><div className="home-principle"><Check size={21}/><p>所有约会角色均为成年人。练习关注真诚表达、相互了解与尊重边界，不提供“她喜欢你的概率”。</p></div>
  </>;
}
